apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: northwind-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: northwin-cronjob-container
            image: "northwin-cronjob-image"
            command: ["/run/monitor.sh"]
          
